/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClarityRouteImport } from './routes/clarity'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as RememberRouteImport } from './routes/remember'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CompassIndexRouteImport } from './routes/compass.index'
import { Route as CompassDecisionIdRouteImport } from './routes/compass.$decisionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarityRoute = ClarityRouteImport.update({
  id: '/clarity',
  path: '/clarity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const RememberRoute = RememberRouteImport.update({
  id: '/remember',
  path: '/remember',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassIndexRoute = CompassIndexRouteImport.update({
  id: '/compass/',
  path: '/compass/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassDecisionIdRoute = CompassDecisionIdRouteImport.update({
  id: '/compass/$decisionId',
  path: '/compass/$decisionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clarity': typeof ClarityRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/progress': typeof ProgressRoute
  '/reflections': typeof ReflectionsRoute
  '/remember': typeof RememberRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/compass/$decisionId': typeof CompassDecisionIdRoute
  '/compass/': typeof CompassIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clarity': typeof ClarityRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/progress': typeof ProgressRoute
  '/reflections': typeof ReflectionsRoute
  '/remember': typeof RememberRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/compass/$decisionId': typeof CompassDecisionIdRoute
  '/compass': typeof CompassIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clarity': typeof ClarityRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/progress': typeof ProgressRoute
  '/reflections': typeof ReflectionsRoute
  '/remember': typeof RememberRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/compass/$decisionId': typeof CompassDecisionIdRoute
  '/compass/': typeof CompassIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clarity'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/how-it-works'
    | '/progress'
    | '/reflections'
    | '/remember'
    | '/reset-password'
    | '/settings'
    | '/support'
    | '/welcome'
    | '/compass/$decisionId'
    | '/compass/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clarity'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/how-it-works'
    | '/progress'
    | '/reflections'
    | '/remember'
    | '/reset-password'
    | '/settings'
    | '/support'
    | '/welcome'
    | '/compass/$decisionId'
    | '/compass'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clarity'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/how-it-works'
    | '/progress'
    | '/reflections'
    | '/remember'
    | '/reset-password'
    | '/settings'
    | '/support'
    | '/welcome'
    | '/compass/$decisionId'
    | '/compass/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClarityRoute: typeof ClarityRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ProgressRoute: typeof ProgressRoute
  ReflectionsRoute: typeof ReflectionsRoute
  RememberRoute: typeof RememberRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  WelcomeRoute: typeof WelcomeRoute
  CompassDecisionIdRoute: typeof CompassDecisionIdRoute
  CompassIndexRoute: typeof CompassIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarity': {
      id: '/clarity'
      path: '/clarity'
      fullPath: '/clarity'
      preLoaderRoute: typeof ClarityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remember': {
      id: '/remember'
      path: '/remember'
      fullPath: '/remember'
      preLoaderRoute: typeof RememberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass/': {
      id: '/compass/'
      path: '/compass'
      fullPath: '/compass/'
      preLoaderRoute: typeof CompassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass/$decisionId': {
      id: '/compass/$decisionId'
      path: '/compass/$decisionId'
      fullPath: '/compass/$decisionId'
      preLoaderRoute: typeof CompassDecisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClarityRoute: ClarityRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  HowItWorksRoute: HowItWorksRoute,
  ProgressRoute: ProgressRoute,
  ReflectionsRoute: ReflectionsRoute,
  RememberRoute: RememberRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  WelcomeRoute: WelcomeRoute,
  CompassDecisionIdRoute: CompassDecisionIdRoute,
  CompassIndexRoute: CompassIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
